FROM archlinux:latest

RUN pacman -Syu --noconfirm
RUN pacman -S --noconfirm \
    base-devel \
    python \
    python-pip \
    curl \
    zstd \
    openssl

COPY . .

RUN LIBZEF_LOCATION=$(realpath core) pip3 install ./python