# This should be run from the zef repo root
FROM archlinux:latest

RUN pacman -Syu --noconfirm
RUN pacman -S --noconfirm \
    base-devel \
    python \
    python-pip \
    curl \
    zstd \
    openssl \
    git \
    jq

RUN pip3 install zef==0.15.7a7
