# This should be run from the zef repo root
FROM debian:stable

COPY . .

RUN apt-get update
RUN apt-get install -y --no-install-recommends \
    cmake \
    curl \
    zstd \
    libzstd-dev \
    openssl \
    libssl-dev \
    libsecret-1-0 \
    libcurl4-openssl-dev \
    python3 \
    python3-pip

RUN LIBZEF_LOCATION=$(realpath core) pip3 install ./python