FROM pengwyn/julia-python-base:jl1.6.0-py3.8-v1.7

# ARG CODEARTIFACT_TOKEN
# ARG GIT_CREDENTIALS
ARG ZEFHUB_AUTH_KEY

# ARG VERSION_STRING
# ARG WITH_JULIA

RUN echo "Building with version string $VERSION_STRING and WITH_JULIA=$WITH_JULIA"

RUN apt-get update
RUN apt-get install -y openssl libssl-dev zstd libzstd-dev libsecret-1-dev

RUN pip3 install absl-py protobuf

COPY . .

# RUN jlpkg registry add https://github.com/synchronoustechnologies/JuliaRegistry

RUN bash make_cleanslate.sh
RUN bash make_everything.sh

# RUN bash setup_tools_wrapper.sh

# RUN twine upload -r codeartifact dist/*
