on: workflow_call
jobs:
  check-license:
    runs-on: "ubuntu-20.04"
    steps:
      - uses: actions/checkout@v3
        #with:
        #  repository: "zefhub/addlicense"
      - uses: actions/setup-go@v3
        with:
          go-version: "^1.13.1"
      - run: go install github.com/zefhub/addlicense@18fa4120a13e50674b12c3d36748fc7d84596dad
      - run: bash .github/scripts/check-license.sh
