on: workflow_call
jobs:
  check-license:
    runs-on: "ubuntu-20.04"
    steps:
      - uses: actions/checkout@v3
        #with:
        #  repository: "zefhub/addlicense"
      - uses: actions/setup-go@v3
        with:
          go-version: "^1.13.1"
      - run: go install github.com/zefhub/addlicense@0dff3a5860a17dabe0678454c9ff70b805a2ea5e
      - run: addlicense -c "Synchronous Technologies Pte Ltd" -f .github/assets/apache-license.md -ignore "_cmake_deps/**" -ignore "cmake_build/**" -ignore ".github/**" -failhard .
