# Same as pyzef-pypi but with a restricted matrix

name: PyPI alpha releases

# Note: we put the dev release in here too as pyzef-pypi.yml is ignoring those.
on:
 push:
   tags:
     - "pyzef-*a*"
     - "pyzef-*dev*"

jobs:
  check-license:
    uses: ./.github/workflows/check-license.yml
  build-wheels:
    if: ${{ !contains(github.ref, 'dev') }}
    needs: check-license
    name: Build wheels
    runs-on: ${{ matrix.os }}
    environment: Release
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-latest, windows-latest]
        # os: [windows-latest]
        # os: [ubuntu-20.04, macos-latest]
        # Note: need "3.10" as yaml will truncate floating point number
        python-version: ["cp39", "cp310", "cp311"]
        # python-version: ["cp39"]
    env:
      # ZEFHUB_AUTH_KEY: "GUEST"
      ZEFHUB_AUTH_KEY: "${{ secrets.TEST_AUTH_KEY }}"

    steps:
      ########
      # Git things
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.11.4
        with:
          package-dir: python
        env:
          CIBW_BUILD: "${{ matrix.python-version}}*"
          # CIBW_BUILD_VERBOSITY: 3

      - name: save wheels in artifacts
        uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: |
            wheelhouse/*

      #######
      # Errors to slack
      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          if_mention: failure
          channel: "#alerts-github-ci"
          fields: repo,message,commit,author,ref,workflow # selectable (default: repo,message)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: ${{ failure() && !contains(github.ref, 'dev') }}

  upload-to-pypi:
    name: Upload wheels to PyPI
    runs-on: ubuntu-20.04
    environment: Release
    needs: [build-wheels]
    # We need this if in case build-wheels doesn't run, because for some reason
    # a skipped status is treated as a reason for the following jobs to also be
    # skipped. Note: github has special checks for any of the
    # "always"/"failed"/etc... expressions, so including always() indicates we
    # are handling it manually here.
    if: ${{ always() && needs.build-wheels.status != 'failure' }}
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Grab built wheels
        if: ${{ !contains(github.ref, 'dev') }}
        uses: actions/download-artifact@v3
        with:
          name: wheels
          path: wheelhouse

      - name: Generate sdist as well
        run: |
          pip3 install --upgrade pip setuptools
          cd python
          python setup.py sdist --dist-dir="../wheelhouse"

      - name: upload to pypi
        env:
          PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
        run: |
          ls -R wheelhouse
          pip3 install --upgrade twine
          python3 -m twine upload -u __token__ -p "${PYPI_TOKEN}" --skip-existing wheelhouse/*
          
  dev-announcement:
    name: Dev announcement
    runs-on: ubuntu-20.04
    needs: [upload-to-pypi]
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          persist-credentials: true

      - name: Get tag
        id: vars
        run: |
          echo "tag=${GITHUB_REF##*/pyzef-}" >> $GITHUB_OUTPUT

      # - name: Release announcement
      #   if: ${{ (!contains(github.ref, 'dev') && github.event.release.prerelease == false) }}
      #   env:
      #     MATTERMOST_URL: ${{ secrets.MATTERMOST_URL }}
      #     CHANNEL: releases
      #     NAME: ${{ github.event.release.name }}
      #     DESCRIPTION: ${{ github.event.release.body }}
      #     VERSION_STRING: ${{ steps.vars.outputs.tag }}
      #     DOWNLOAD_STRING: "`pip3 install --upgrade zef`"
      #   run: go run ${GITHUB_WORKSPACE}/.github/scripts/publish_release_announcement.go

      - name: Release announcement for dev
        env:
          MATTERMOST_URL: ${{ secrets.MATTERMOST_URL }}
          CHANNEL: "dev-releases"
          NAME: ${{ steps.vars.outputs.tag }}
          DESCRIPTION_FILE: "release.body"
          VERSION_STRING: ${{ steps.vars.outputs.tag }}
          DOWNLOAD_STRING: "`pip install zef==${{ steps.vars.outputs.tag }}`"
        run: |
          echo "Alpha/dev release of PyPI wheels for version ${VERSION_STRING}" > release.body
          go run ${GITHUB_WORKSPACE}/.github/scripts/publish_release_announcement.go
